# Database connection settings
url=jdbc:postgresql://localhost:5432/minibank-database
username=postgres
password=postgres

# Path to the changelog file
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml

# Driver class
driver=org.postgresql.Driver

# Optional: Default schema (if applicable)
defaultSchemaName=public

