= Minibank
EMeMSoft spol s r.o. <miroslav.mamrak@seznam.cz>
:revnumber: v0.1
:revdate: 15-01.2024
:revremark: First version of the document

Example project in Spring Boot 3.4.1 with Kotlin and built by Gradle.

== Prerequisites

Install Docker and docker-compose on a system where you want to run this project.

- run database with

[bash]
----
docker-compose up -d postgres
----

- create schema `bank` in your PostgreSQL database

[bash]
----
docker-compose exec postgres psql -U postgres -c "CREATE SCHEMA bank"
----

// You must have docker and docker-compose installed on a system where you want to run this project.
// Also if you want to use GraalVM native image, you must have GraalVM JDK installed on your system.
// Next you must generate metadata for native image as described in documentation: https://graalvm.github.io/native-build-tools/latest/gradle-plugin-quickstart.html[GraalVM Quickstart Documentation]
// https://graalvm.github.io/native-build-tools/latest/gradle-plugin-quickstart.html#build-a-native-executable-with-resources-autodetection[Gradle Native Image Plugin Documentation]
// Create schema 'bank' in your PostgreSQL database.

== Build

`./gradlew clean bootBuildImage`

== How to run

Database should be already running since schema creation.
Now you can run the application with

[bash]
----
docker-compose up -d
----

application should be accepting requests on `http://localhost:8082`

image::https://github.com/mamrakm/minibank/actions/workflows/github-actions.yml/badge.svg[Build Status]