spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minibank-database
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/minibank-database?schema=bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
server:
  port: 8888
logging:
  level:
    root: INFO
    cz.ememsoft.minibank: DEBUG
    org.springframework: ERROR
    reactor: WARN
    org.springframework.r2dbc: WARN
