spring:
  application:
    name: minibank
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: bank
    # Configure Liquibase to work with R2DBC setup
    url: jdbc:postgresql://localhost:5432/minibank-database?schema=bank
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/minibank
          jwk-set-uri: http://localhost:8080/realms/minibank/protocol/openid-connect/certs
  task:
    execution:
      pool:
        core-size: 5          # Minimum number of threads
        max-size: 10          # Maximum number of threads
        queue-capacity: 25    # Size of the queue for pending tasks
        allow-core-thread-timeout: true # Allow core threads to time out
      thread-name-prefix: "AsyncExecutor-" # Custom thread name prefix

keycloak:
  base-url: http://localhost:8080
  realm: minibank
  client-id: minibank-api
  client-secret: minibank-secret
  admin-realm: master
