spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minibank-database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

server:
  port: 8082
