package cz.ememsoft.minibank.mapper

import cz.ememsoft.minibank.api.client.request.CreateClientRequestDto
import cz.ememsoft.minibank.api.client.response.CreateClientResponseDto
import cz.ememsoft.minibank.dto.ClientDto
import cz.ememsoft.minibank.entity.ClientEntity
import org.mapstruct.Mapper
import org.mapstruct.Mapping
import org.mapstruct.MappingConstants

/**
 * Mapper interface for converting between Client entities and Data Transfer Objects (DTOs).
 *
 * This interface leverages MapStruct to automatically generate the mapping implementations
 * for converting between ClientEntity and various DTOs with explicit mappings.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
interface ClientMapper {

    /**
     * Converts a ClientEntity to a ClientDto with explicit field mappings.
     */
    @Mapping(source = "id", target = "id")
    @Mapping(source = "firstName", target = "firstName")
    @Mapping(source = "lastName", target = "lastName")
    @Mapping(source = "email", target = "email")
    @Mapping(source = "phoneNumber", target = "phoneNumber")
    @Mapping(source = "address", target = "address")
    @Mapping(source = "dateOfBirth", target = "dateOfBirth")
    @Mapping(source = "personalNumber", target = "personalNumber")
    fun entityToDto(clientEntity: ClientEntity): ClientDto

    /**
     * Converts a ClientDto to a ClientEntity with explicit field mappings.
     */
    @Mapping(source = "id", target = "id")
    @Mapping(source = "firstName", target = "firstName")
    @Mapping(source = "lastName", target = "lastName")
    @Mapping(source = "email", target = "email")
    @Mapping(source = "phoneNumber", target = "phoneNumber")
    @Mapping(source = "address", target = "address")
    @Mapping(source = "dateOfBirth", target = "dateOfBirth")
    @Mapping(source = "personalNumber", target = "personalNumber")
    fun dtoToEntity(clientDto: ClientDto): ClientEntity

    /**
     * Converts a CreateClientRequestDto to a partial ClientEntity with explicit field mappings.
     * - The 'id' field is ignored as it will be generated by the database.
     * - The 'personalNumber' field is ignored as it will be auto-generated as UUID.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "personalNumber", ignore = true)
    @Mapping(source = "firstName", target = "firstName")
    @Mapping(source = "lastName", target = "lastName")
    @Mapping(source = "email", target = "email")
    @Mapping(source = "phoneNumber", target = "phoneNumber")
    @Mapping(source = "address", target = "address")
    @Mapping(source = "dateOfBirth", target = "dateOfBirth")
    fun createRequestToEntity(createClientRequestDto: CreateClientRequestDto): ClientEntity

    /**
     * Converts a ClientEntity to a CreateClientResponseDto with explicit field mappings.
     */
    @Mapping(source = "id", target = "id")
    @Mapping(source = "firstName", target = "firstName")
    @Mapping(source = "lastName", target = "lastName")
    @Mapping(source = "email", target = "email")
    @Mapping(source = "phoneNumber", target = "phoneNumber")
    @Mapping(source = "address", target = "address")
    @Mapping(source = "dateOfBirth", target = "dateOfBirth")
    @Mapping(source = "personalNumber", target = "personalNumber")
    fun entityToCreateResponse(clientEntity: ClientEntity): CreateClientResponseDto

    /**
     * Converts a list of ClientEntity to a list of ClientDto.
     */
    fun entitiesToDtos(clientEntities: List<ClientEntity>): List<ClientDto>

    /**
     * Converts a list of ClientDto to a list of ClientEntity.
     */
    fun dtosToEntities(clientDtos: List<ClientDto>): List<ClientEntity>
}