package cz.ememsoft.minibank.entity

import cz.ememsoft.minibank.enumeration.ClientStatusEnum
import cz.ememsoft.minibank.enumeration.UserRoleEnum
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Past
import jakarta.validation.constraints.Pattern
import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.UUID

/**
 * Client entity representing a bank customer in the system.
 *
 * Maps to the 'client' table in the 'bank' schema. Contains all customer
 * personal information required for banking operations, including KYC compliance.
 *
 * @property id Primary key, auto-generated
 * @property firstName Customer’s legal first name
 * @property lastName Customer’s legal last name
 * @property email Unique email address for customer communication
 * @property phoneNumber Optional contact phone number in international format
 * @property address Optional residential address
 * @property dateOfBirth Date of birth for age verification and compliance
 * @property personalNumber Unique UUID for internal customer identification
 */
@Table("client", schema = "bank")
data class ClientEntity(
    /**
     * Primary key - auto-generated by database sequence
     */
    @Id
    @NotBlank
    val id: Long,

    /**
     * Customer's legal first name
     * Required for all banking operations and legal compliance
     */
    @Column("first_name")
    @NotBlank(message = "First name must not be blank")
    val firstName: String,

    /**
     * Customer's legal last name
     * Required for all banking operations and legal compliance
     */
    @Column("last_name")
    @NotBlank(message = "Last name must not be blank")
    val lastName: String,

    /**
     * Primary email address for customer communication and authentication
     * Must be unique across all customers in the system
     */
    @Column("email")
    @NotBlank(message = "Email must not be blank")
    @Email(message = "Email must be valid")
    @Pattern(
        regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
        message = "Email format is invalid"
    )
    val email: String,

    /**
     * BCrypt encoded password hash for authentication
     * Never store plain text passwords
     */
    @Column("password_hash")
    @NotBlank(message = "Password hash must not be blank")
    val passwordHash: String,

    /**
     * User role determining access level
     * CLIENT: Can only access their own data
     * ADMIN: Can access all data and admin endpoints
     */
    @Column("role")
    val role: UserRoleEnum = UserRoleEnum.CLIENT,

    /**
     * Optional contact phone number
     * Should follow an international format when provided
     */
    @Column("phone_number")
    val phoneNumber: String?,

    /**
     * Optional residential address
     * Used for correspondence and compliance purposes
     */
    @Column("address")
    val address: String?,

    /**
     * Date of birth for age verification
     * Required for KYC compliance and service eligibility
     */
    @Column("date_of_birth")
    @Past(message = "Date of birth must be in the past")
    val dateOfBirth: LocalDate?,

    /**
     * Unique internal customer identifier
     * Auto-generated UUID for secure customer referencing
     */
    @Column("personal_number")
    val personalNumber: UUID? = null,

    /**
     * Client status for soft delete functionality
     * Banking systems cannot delete client records for audit compliance
     */
    @Column("status")
    val status: ClientStatusEnum = ClientStatusEnum.ACTIVE,

    /**
     * Whether the account is enabled for login
     * Can be used to disable accounts without changing status
     */
    @Column("enabled")
    val enabled: Boolean = true,

    /**
     * Account creation timestamp
     */
    @Column("created_at")
    val createdAt: LocalDateTime = LocalDateTime.now(),

    /**
     * Last successful login timestamp
     */
    @Column("last_login_at")
    val lastLoginAt: LocalDateTime? = null
)