-- liquibase formatted sql

-- changeset miroslav.mamrak:1737470944023-1
CREATE TABLE bank.account
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  BIGINT                                  NOT NULL,
    balance    DECIMAL                                 NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

-- changeset miroslav.mamrak:1737470944023-2
CREATE TABLE bank.client
(
    client_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

-- changeset miroslav.mamrak:1737470944023-3
ALTER TABLE bank.client
    ADD CONSTRAINT uc_client_email UNIQUE (email);

-- changeset miroslav.mamrak:1737470944023-4
ALTER TABLE bank.account
    ADD CONSTRAINT FK_ACCOUNT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES bank.client (client_id);

