-- liquibase formatted sql

-- changeset 1453c:1736889098667-1
CREATE TABLE customer
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    phone       VARCHAR(255)                            NOT NULL,
    address     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

-- changeset 1453c:1736889098667-2
ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);
