package cz.ememsoft.minibank.service

import cz.ememsoft.minibank.dto.auth.AuthResponseDto
import cz.ememsoft.minibank.dto.auth.LoginRequestDto
import cz.ememsoft.minibank.dto.auth.RegisterRequestDto
import cz.ememsoft.minibank.entity.ClientEntity
import cz.ememsoft.minibank.exception.ClientNotFoundException
import cz.ememsoft.minibank.exception.DuplicateClientException
import cz.ememsoft.minibank.exception.InvalidClientDataException
import cz.ememsoft.minibank.repository.ClientRepository
import io.github.oshai.kotlinlogging.KotlinLogging
import io.jsonwebtoken.Claims
import io.jsonwebtoken.Jwts
import io.jsonwebtoken.SignatureAlgorithm
import io.jsonwebtoken.security.Keys
import org.springframework.beans.factory.annotation.Value
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.stereotype.Service
import reactor.core.publisher.Mono
import java.time.LocalDateTime
import java.util.Date
import java.util.UUID

private val logger = KotlinLogging.logger {}

@Service
class AuthenticationServiceImpl(
    private val clientRepository: ClientRepository,
    @Value("\${jwt.secret:defaultSecretKeyThatShouldBeChangedInProduction1234567890}")
    private val jwtSecret: String,
    @Value("\${jwt.expiration:86400}") // 24 hours in seconds
    private val jwtExpiration: Long
) : AuthenticationService {

    private val passwordEncoder = BCryptPasswordEncoder()
    private val secretKey = Keys.hmacShaKeyFor(jwtSecret.toByteArray())

    override fun register(registerRequest: RegisterRequestDto): Mono<AuthResponseDto> {
        logger.info { "Attempting to register client with email: ${registerRequest.email}" }

        // Check if email already exists
        return clientRepository.findByEmail(registerRequest.email)
            .hasElement()
            .flatMap { exists ->
                if (exists) {
                    logger.warn { "Registration failed: Email ${registerRequest.email} already exists" }
                    Mono.error(DuplicateClientException("Email ${registerRequest.email} is already registered"))
                } else {
                    createClient(registerRequest)
                }
            }
    }

    private fun createClient(registerRequest: RegisterRequestDto): Mono<AuthResponseDto> {
        val encodedPassword = encodePassword(registerRequest.password)
        val personalNumber = UUID.randomUUID()
        val now = LocalDateTime.now()

        val clientEntity = ClientEntity(
            id = 0, // Will be generated by database
            firstName = registerRequest.firstName,
            lastName = registerRequest.lastName,
            email = registerRequest.email,
            passwordHash = encodedPassword,
            role = registerRequest.role,
            phoneNumber = registerRequest.phoneNumber,
            address = registerRequest.address,
            dateOfBirth = registerRequest.dateOfBirth,
            personalNumber = personalNumber,
            enabled = true,
            createdAt = now,
            lastLoginAt = null
        )

        return clientRepository.save(clientEntity)
            .doOnSuccess { logger.info { "Successfully registered client with ID: ${it.id}" } }
            .map { savedClient ->
                val token = generateToken(savedClient.id, savedClient.email, savedClient.role.name)
                AuthResponseDto(
                    token = token,
                    clientId = savedClient.id,
                    email = savedClient.email,
                    role = savedClient.role,
                    expiresIn = jwtExpiration
                )
            }
            .doOnError { logger.error(it) { "Error during client registration" } }
    }

    override fun login(loginRequest: LoginRequestDto): Mono<AuthResponseDto> {
        logger.info { "Attempting login for email: ${loginRequest.email}" }

        return clientRepository.findByEmail(loginRequest.email)
            .switchIfEmpty(Mono.error(ClientNotFoundException("Invalid email or password")))
            .flatMap { client ->
                if (!client.enabled) {
                    logger.warn { "Login failed: Account disabled for email ${loginRequest.email}" }
                    Mono.error(InvalidClientDataException("Account is disabled"))
                } else if (!verifyPassword(loginRequest.password, client.passwordHash)) {
                    logger.warn { "Login failed: Invalid password for email ${loginRequest.email}" }
                    Mono.error(ClientNotFoundException("Invalid email or password"))
                } else {
                    updateLastLogin(client)
                }
            }
    }

    private fun updateLastLogin(client: ClientEntity): Mono<AuthResponseDto> {
        val updatedClient = client.copy(lastLoginAt = LocalDateTime.now())
        
        return clientRepository.save(updatedClient)
            .map { savedClient ->
                logger.info { "Successful login for client ID: ${savedClient.id}" }
                val token = generateToken(savedClient.id, savedClient.email, savedClient.role.name)
                AuthResponseDto(
                    token = token,
                    clientId = savedClient.id,
                    email = savedClient.email,
                    role = savedClient.role,
                    expiresIn = jwtExpiration
                )
            }
    }

    override fun generateToken(clientId: Long, email: String, role: String): String {
        val now = Date()
        val expiryDate = Date(now.time + jwtExpiration * 1000)

        return Jwts.builder()
            .setSubject(clientId.toString())
            .claim("email", email)
            .claim("role", role)
            .setIssuedAt(now)
            .setExpiration(expiryDate)
            .signWith(secretKey, SignatureAlgorithm.HS512)
            .compact()
    }

    override fun validateToken(token: String): Mono<Long> {
        return try {
            val claims: Claims = Jwts.parser()
                .verifyWith(secretKey)
                .build()
                .parseSignedClaims(token)
                .payload

            val clientId = claims.subject.toLong()
            Mono.just(clientId)
        } catch (e: Exception) {
            logger.warn { "Invalid JWT token: ${e.message}" }
            Mono.empty()
        }
    }

    override fun encodePassword(password: String): String {
        return passwordEncoder.encode(password)
    }

    override fun verifyPassword(password: String, encodedPassword: String): Boolean {
        return passwordEncoder.matches(password, encodedPassword)
    }
}