/*
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Author: EMeMSoft spol. s r.o.
 * 06/02/2025, 22:38
 */

-- liquibase formatted sql

-- changeset 1453c:1738877893772-1
CREATE TABLE bank.account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_name VARCHAR(255)                            NOT NULL,
    client_id    BIGINT                                  NOT NULL,
    balance      DECIMAL                                 NOT NULL,
    account_type SMALLINT                                NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

-- changeset 1453c:1738877893772-2
CREATE TABLE bank.client
(
    client_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

-- changeset 1453c:1738877893772-3
ALTER TABLE bank.client
    ADD CONSTRAINT uc_client_email UNIQUE (email);

-- changeset 1453c:1738877893772-4
ALTER TABLE bank.account
    ADD CONSTRAINT FK_ACCOUNT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES bank.client (client_id);

